High value dataset support and dependency updates
IDgis/RDW_INSPIRE pull request #55
Opened 2024-09-11 14:49 UTC by HermanAssink

2024-09-12 08:01 UTC, KevinvdBosch requested changes

2024-09-12 08:03 UTC, HermanAssink commented on awstats/awstats.inspire.rdw.nl.conf
> +HostAliases="inspire.rdw.localhost 127.0.0.1"
Welke problemen verwacht jij? Ik heb dat aangepast omdat deze domeinen m.i. niet meer worden gebruikt.

2024-09-12 08:06 UTC, HermanAssink commented on nginx/default.conf
> +    server rdw_inspire-geoserver-1:8080;
Gebruik van de service-naam werkte niet bij mij als het netwerk extern is. Het netwerk moet denk ik extern zijn voor de ogr2ogr en hale container? Moeten we dit misschien variabel maken vanwege de verschillende docker versies in ontwikkel- en productieomgeving?

2024-09-12 08:07 UTC, HermanAssink commented on nginx/default.conf
> +    server rdw_inspire-awstats-1:80;
Zie reactie bij geoserver

2024-09-12 08:08 UTC, HermanAssink commented on nginx/default.conf
> +    server_name inspire.rdw.localhost inspire.rdw.nl;
Nee, dat is niet nodig. De applicatie moet op productie alleen toegankelijk zijn via inspire.rdw.nl

2024-09-12 08:18 UTC, KevinvdBosch commented on nginx/default.conf
> +    server rdw_inspire-geoserver-1:8080;
Je zou zelf lokaal ook een script start script kunnen maken die bijvoorbeeld de volgende regel bevat:
```shell
#!/bin/bash
docker compose --compatibility -p rdw up -d
```

Dit maakt de containers op de oude manier, waardoor je zelf ook kunt testen met `rdw_geoserver_1`.

2024-09-12 08:19 UTC, KevinvdBosch commented on nginx/default.conf
> +    server rdw_inspire-awstats-1:80;
Zie reactie bij geoserver

2024-09-12 08:38 UTC, HermanAssink commented on nginx/default.conf
> +    server rdw_inspire-geoserver-1:8080;
Doe ik

2024-09-13 12:00 UTC, KevinvdBosch approved these changes

2024-09-26 07:49 UTC, KevinvdBosch commented on ogr2ogr/Dockerfile
> +# CMD ["sh", "-c", "while :; do sleep 2073600; done"]
Moet deze uitgecommentarieerde code blijven staan?

2024-09-26 07:51 UTC, KevinvdBosch commented on ogr2ogr/refresh-scripts/refresh-data.sh
> +docker run --rm -i --name  rdw_hale_1 --network $NETWORK_NAME --volumes-from $NGINX_CONTAINER idgis/rdw_hale:$HALE_IMAGE_VERSION
Waarom is de image veranderd? Het is beter om de eerder gebouwde image uit docker hub te gebruiken om er zeker van te zijn dat hij het altijd blijft doen

2024-09-26 07:53 UTC, KevinvdBosch commented on ogr2ogr/Dockerfile
> +RUN apt-get update && apt-get install -y docker.io
Waarom wordt docker in de container geïnstalleerd? Volgens mij wordt de Docker op de host aangeroepen, aangezien daar de hale container moet gaan draaien

2024-09-26 07:56 UTC, HermanAssink commented on ogr2ogr/Dockerfile
> +# CMD ["sh", "-c", "while :; do sleep 2073600; done"]
Wel handig dat je om in een running container te kunnen kijken of de voorgaande (installatie-)stappen goed zijn gegaan als de run/init tot een restart leiden. Dit is een simpeler commando om dat te bereiken: #CMD tail -f /dev/null

2024-09-26 08:01 UTC, HermanAssink commented on ogr2ogr/refresh-scripts/refresh-data.sh
> +docker run --rm -i --name  rdw_hale_1 --network $NETWORK_NAME --volumes-from $NGINX_CONTAINER idgis/rdw_hale:$HALE_IMAGE_VERSION
Zodat images allemaal dezelfde naam hebben, namelijk rdw_<component>. De image idgis/rdw_hale:3.0.0 heb ik op m'n laptop zo benoemd en getagd zodat als deze op DockerHub onder idgis met tag 3.0.0 wordt geplaatst in de prod-omgeving deze automatisch van DockerHub wordt gehaald.

2024-09-26 08:06 UTC, HermanAssink commented on ogr2ogr/Dockerfile
> +RUN apt-get update && apt-get install -y docker.io
Klopt, docker op de host wordt aangeroepen. Ik heb het gewijzigd omdat de volume mapping van docker op de host naar de container niet meer werkte en zo'n mapping volgens Reijer minder robuust is dan de docker client in de container installeren. Draait er na apt-get install -y docker.io ook een docker deamon in de container? het werkt in in ieder geval wel zoals bedoeld, docker commando's in de container roepen de deamon op de host aan.

2024-09-26 08:12 UTC, KevinvdBosch commented on ogr2ogr/Dockerfile
> +RUN apt-get update && apt-get install -y docker.io
> Ik heb het gewijzigd omdat de volume mapping van docker op de host naar de container niet meer werkte

Dan moeten we op de productie omgeving wel goed kijken of dit geen problemen geeft

2024-09-26 14:35 UTC, KevinvdBosch approved these changes

2024-10-01 09:17 UTC, merged